### ISSUE TITLE
Storage File of IE View WE

### ISSUE THREAD

**Issue by dave6700** [clear-code/ieview-we#35] opened 2019-11-13 09:21 UTC
Hello,

where does IE View WE store the links which should be opened in IE ? Is there a configuration file or Registry key for this ?

**Comment by piroor** [comment] 2020-07-01 02:33
IE View WE uses `browser.storage.local` API for extensions. Sadly we addon author don't know details abouthow they are treated by the browser, but it looks to be stored in an IndexedDB storage internally on lately versions of Firefox.

If you need to control the list of URLs from outside of Firefox (or Chrome), a [managed storage](https://developer.chrome.com/extensions/manifest/storage) may help you. If any managed storage is provided, IE View WE loads options from it automatically. Here is examples: https://github.com/clear-code/ieview-we/tree/master/managed-storage

**Comment by piroor** [comment] 2020-07-01 02:50
I close this for now because this looks to be not a bug report.

**Closed by piroor** 2020-07-01 02:50 UTC
